holyhansss

medium

# Excess eth is not refunded

## Summary

## Vulnerability Detail
The WalletImpl.sol contract requires sender to provide eth(msg.value) when calling WalletImpl.execCalls(). Now if user has provided more eth than combined call.value then this excess eth is not refunded back to user.

1. Observe the [execCalls() function](https://github.com/0xSplits/splits-utils/blob/e61c4f8f7aaa31e0dada40fc96b4237afb6d3fe1/src/WalletImpl.sol#L43-L65)

```solidity
function execCalls(Call[] calldata calls_)
        external
        payable
        onlyOwner
        returns (uint256 blockNumber, bytes[] memory returnData)
    {

				...
        for (uint256 i; i < length;) {
            Call calldata calli = calls_[i];
            (success, returnData[i]) = calli.to.call{value: calli.value}(calli.data);
            require(success, string(returnData[i]));

            unchecked {
                ++i;
            }
        }

        emit ExecCalls(calls_);
    }
```

1. As we can see user provided msg.value is deducted with each calli.value
2. Assume user provided 5 amount as msg.value and made a single call with calls[0].value as 4
3. This means after calls have been completed ethAvailable will become 5-4=1
4. Ideally this 1 eth should be refunded back to user but there is no provision for same and the fund will remain in contract

## Impact
User will not get a refund for exceeding msg.value.

## Code Snippet
https://github.com/0xSplits/splits-utils/blob/e61c4f8f7aaa31e0dada40fc96b4237afb6d3fe1/src/WalletImpl.sol#L43-L65

## Tool used
Manual Review

## Recommendation
add this line of code at the end of execCalls()

```solidity
payable(msg.sender).call{value: address(this).balance}("");
require(success, "msg.sender cannot receive exceed value");
```